sudo: required
services: 
  - docker

before_install: 
  - docker build -t timothygit922/new-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true timothygit922/new-docker-react  npm run test